[package]
name = "resistance-advisor"
version = "0.1.0"
edition = "2021"

[dependencies]
json = "0.12.4"
log = "0.4.22"
multi_log = "0.1.2"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
simplelog = "0.12.2"
syslog = "7.0.0"
